name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'src/**'
      - 'build/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'src/**'
      - 'build/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: build/package.json
        
    - name: Install system dependencies for Puppeteer
      run: |
        # Update package list
        sudo apt-get update
        
        # Install Chrome stable
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Install additional dependencies
        sudo apt-get install -y \
          fonts-liberation \
          libxss1 \
          libgconf-2-4 \
          libxtst6 \
          libxrandr2 \
          libasound2 \
          libpangocairo-1.0-0 \
          libatk1.0-0 \
          libcairo-gobject2 \
          libgtk-3-0 \
          libgdk-pixbuf2.0-0
        
    - name: Install dependencies
      run: |
        cd build
        npm ci
        
    - name: Test Puppeteer setup
      env:
        CI: true
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
      run: |
        cd build
        node test-puppeteer.js
        
    - name: Build site
      env:
        CI: true
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
      run: |
        cd build
        # Try normal build first, fallback if Puppeteer fails
        npm run build || npm run build-safe
        
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./dist

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
